/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int LET = 6;
  /** RegularExpression Id. */
  int TYPE = 7;
  /** RegularExpression Id. */
  int TRUE = 8;
  /** RegularExpression Id. */
  int FALSE = 9;
  /** RegularExpression Id. */
  int PIPE = 10;
  /** RegularExpression Id. */
  int PLUS = 11;
  /** RegularExpression Id. */
  int MINUS = 12;
  /** RegularExpression Id. */
  int STAR = 13;
  /** RegularExpression Id. */
  int DIV = 14;
  /** RegularExpression Id. */
  int LPAR = 15;
  /** RegularExpression Id. */
  int RPAR = 16;
  /** RegularExpression Id. */
  int LBRA = 17;
  /** RegularExpression Id. */
  int RBRA = 18;
  /** RegularExpression Id. */
  int EQUAL = 19;
  /** RegularExpression Id. */
  int DOT = 20;
  /** RegularExpression Id. */
  int COLON = 21;
  /** RegularExpression Id. */
  int DCOLON = 22;
  /** RegularExpression Id. */
  int LCOLON = 23;
  /** RegularExpression Id. */
  int SEMIC = 24;
  /** RegularExpression Id. */
  int TERM = 25;
  /** RegularExpression Id. */
  int COMMA = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int OR = 28;
  /** RegularExpression Id. */
  int EQ = 29;
  /** RegularExpression Id. */
  int GT = 30;
  /** RegularExpression Id. */
  int LT = 31;
  /** RegularExpression Id. */
  int GE = 32;
  /** RegularExpression Id. */
  int LE = 33;
  /** RegularExpression Id. */
  int NEQ = 34;
  /** RegularExpression Id. */
  int NOT = 35;
  /** RegularExpression Id. */
  int ASSIGN = 36;
  /** RegularExpression Id. */
  int BOX = 37;
  /** RegularExpression Id. */
  int NIL = 38;
  /** RegularExpression Id. */
  int DEREF = 39;
  /** RegularExpression Id. */
  int IF = 40;
  /** RegularExpression Id. */
  int ELSE = 41;
  /** RegularExpression Id. */
  int WHILE = 42;
  /** RegularExpression Id. */
  int PRINT = 43;
  /** RegularExpression Id. */
  int PRINTLN = 44;
  /** RegularExpression Id. */
  int FN = 45;
  /** RegularExpression Id. */
  int ARROW = 46;
  /** RegularExpression Id. */
  int SARROW = 47;
  /** RegularExpression Id. */
  int MATCH = 48;
  /** RegularExpression Id. */
  int INT = 49;
  /** RegularExpression Id. */
  int UNIT = 50;
  /** RegularExpression Id. */
  int BOOL = 51;
  /** RegularExpression Id. */
  int STRING = 52;
  /** RegularExpression Id. */
  int LIST = 53;
  /** RegularExpression Id. */
  int REF = 54;
  /** RegularExpression Id. */
  int UNION = 55;
  /** RegularExpression Id. */
  int STRUCT = 56;
  /** RegularExpression Id. */
  int String = 57;
  /** RegularExpression Id. */
  int Id = 58;
  /** RegularExpression Id. */
  int Label = 59;
  /** RegularExpression Id. */
  int Num = 60;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "\"let\"",
    "\"type\"",
    "\"true\"",
    "\"false\"",
    "\"|\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\".\"",
    "\":\"",
    "\"::\"",
    "\":?\"",
    "\";\"",
    "\";;\"",
    "\",\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "<NEQ>",
    "\"~\"",
    "\":=\"",
    "\"box\"",
    "\"nil\"",
    "\"!\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"print\"",
    "\"println\"",
    "\"fn\"",
    "\"=>\"",
    "\"->\"",
    "\"match\"",
    "\"int\"",
    "<UNIT>",
    "\"bool\"",
    "\"string\"",
    "\"list\"",
    "\"ref\"",
    "\"union\"",
    "\"struct\"",
    "<String>",
    "<Id>",
    "<Label>",
    "<Num>",
  };

}
